//! Hex helpers for CLI inputs.
//!
//! [`hex_to_bytes`] is the lenient CLI-input decoder: it accepts an optional
//! `0x`/`0X` prefix and either case, and rejects odd-length / non-hex input. It
//! is shared by both non-secret inputs (`--hash`, signature bytes, Merkle
//! leaves) and secret inputs (recipient secret keys, identity seeds), so its
//! error messages report only the input *length* and the *offset* of the first
//! invalid byte — never the value itself. Echoing the value would leak key
//! material into terminals, shell history, and CI logs whenever the decoded
//! input was a seed or secret key. This is intentionally more forgiving than the
//! SDK's strict lowercase decoder, which is fed machine-generated bytes.
//!
//! [`bytes_to_hex`] re-exports the single SDK encoder so CLI output stays
//! byte-identical to the SDK's hex form (lowercase, no separators).

/// Encode bytes to lowercase hex with no separators (the SDK encoder).
#[must_use]
pub fn bytes_to_hex(bytes: &[u8]) -> String {
    cardanowall::hex::encode(bytes)
}

/// Decode a lenient hex string: an optional `0x`/`0X` prefix, either case.
///
/// # Errors
///
/// Returns an error message string for odd-length or non-hex input. The message
/// describes only the input length and the offset of the first invalid byte; it
/// never reproduces the input itself, because this decoder is shared by the
/// secret-carrying paths (seeds, recipient secret keys).
pub fn hex_to_bytes(input: &str) -> Result<Vec<u8>, String> {
    let clean = input
        .strip_prefix("0x")
        .or_else(|| input.strip_prefix("0X"))
        .unwrap_or(input);
    if !clean.len().is_multiple_of(2) {
        return Err(format!("invalid hex: odd length ({} chars)", clean.len()));
    }
    if let Some(offset) = clean.bytes().position(|b| !b.is_ascii_hexdigit()) {
        return Err(format!(
            "invalid hex: non-hex char at offset {offset} in {}-char input",
            clean.len()
        ));
    }
    hex::decode(clean).map_err(|_| {
        format!(
            "invalid hex: {}-char input could not be decoded",
            clean.len()
        )
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trips_lowercase() {
        let bytes = [0xde, 0xad, 0xbe, 0xef];
        assert_eq!(bytes_to_hex(&bytes), "deadbeef");
        assert_eq!(hex_to_bytes("deadbeef").unwrap(), bytes);
    }

    #[test]
    fn accepts_0x_prefix_and_uppercase() {
        assert_eq!(hex_to_bytes("0xDEAD").unwrap(), vec![0xde, 0xad]);
        assert_eq!(hex_to_bytes("0XdeAd").unwrap(), vec![0xde, 0xad]);
    }

    #[test]
    fn rejects_odd_length() {
        let err = hex_to_bytes("abc").unwrap_err();
        assert!(err.contains("odd length"));
        assert!(err.contains("3 chars"));
        // The offending input must NOT appear in the message.
        assert!(!err.contains("abc"));
    }

    #[test]
    fn rejects_non_hex() {
        // First valid hex char then an invalid one at offset 2.
        let err = hex_to_bytes("abzz").unwrap_err();
        assert!(err.contains("non-hex char"));
        assert!(err.contains("offset 2"));
        assert!(err.contains("4-char input"));
    }

    #[test]
    fn error_never_leaks_a_secret_looking_input() {
        // A 64-char secret-shaped value with one stray non-hex byte: the error
        // must reveal only the length and the offset, never the input bytes.
        let mut secret = "ab".repeat(31);
        secret.push_str("ax"); // 64 chars, invalid byte at offset 63
        let err = hex_to_bytes(&secret).unwrap_err();
        assert!(!err.contains(&secret));
        assert!(!err.contains(&"ab".repeat(31)));
        assert!(err.contains("offset 63"));
        assert!(err.contains("64-char input"));
    }
}
